image: registry.gitlab.com/islandoftex/images/texlive:latest

build:
  script:
    - pdflatex statuten_grazer_linuxtage.tex
    - pdflatex statuten_grazer_linuxtage.tex
  after_script:
    - cat statuten_grazer_linuxtage.log
  artifacts:
    paths:
      - statuten_grazer_linuxtage.pdf
