name: Build LaTeX document
on:
  pull_request:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: statuten_grazer_linuxtage.tex
          compiler: lualatex
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: statuten_grazer_linuxtage.tex
          compiler: lualatex
      - name: Upload binaries to action
        uses: actions/upload-artifact@v4
        with:
          name: Statuten Grazer Linuxtage
          path: statuten_grazer_linuxtage.pdf