name: Build LaTeX document
on:
  push:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: statuten_grazer_linuxtage.tex
          compiler: lualatex
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: statuten_grazer_linuxtage.tex
          compiler: lualatex
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: statuten_grazer_linuxtage.pdf
          asset_name: Statuten Grazer Linuxtage
          tag: ${{ github.ref }}
          overwrite: true